name: banana_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  lottie: ^1.4.0

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  unicons: ^2.1.0
  flutter_expandable_fab: ^1.7.1
  animated_icon: ^0.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
